import Head from "next/head";

import Faq from "../components/Faq";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LogoCloud from "../components/LogoCloud";
import Pricing from "../components/Pricing";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative bg-white">
        <Header />
        <Pricing />
        <LogoCloud />
        <Faq />
        <Footer />
      </div>
    </div>
  );
}
